# Generated by Django 4.1.7 on 2023-04-24 22:53

import Shipping_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveIntegerField(default=Shipping_app.models.auto_id, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'ItemsAPI',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.PositiveIntegerField(default=Shipping_app.models.auto_id, primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='User_Basket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='list_item', to='Shipping_app.item')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='list_shipment', to='Shipping_app.shipment')),
            ],
        ),
    ]
